# Generated by Django 4.2.2 on 2023-06-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_code', models.IntegerField()),
                ('school_name', models.CharField(max_length=200)),
                ('school_head', models.CharField(max_length=200)),
                ('Mobile_number', models.IntegerField()),
                ('Location', models.CharField(max_length=500)),
            ],
        ),
    ]
