# Generated by Django 4.2.2 on 2023-06-29 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nj_contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Mobile_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number should have 10 digits and start with 0 e.g. 0xxxxxxxxx', regex='^0\\d{9}$')]),
        ),
    ]
