# Generated by Django 4.2.2 on 2023-06-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nj_contacts', '0002_alter_contact_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Type_of_School',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default=None, max_length=1),
        ),
    ]
