# Generated by Django 4.2.2 on 2023-06-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nj_contacts', '0003_contact_type_of_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Mobile_number',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Type_of_School',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=True, max_length=254),
            preserve_default=False,
        ),
    ]
