# Generated by Django 4.2.2 on 2023-06-30 07:14

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Nj_contacts', '0004_remove_contact_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='mobile_number',
            field=models.CharField(default=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number should have 10 digits and start with 0 e.g. 0xxxxxxxxx', regex='^0\\d{9}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='type_of_school',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE')], default=True, max_length=20),
            preserve_default=False,
        ),
    ]
