# Generated by Django 4.2.2 on 2023-07-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nj_contacts', '0005_contact_created_at_contact_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='school_category',
            field=models.CharField(choices=[('PRIMARY', 'PRIMARY'), ('SECONDARY', 'SECONDARY')], default=True, max_length=20),
            preserve_default=False,
        ),
    ]
