# Generated by Django 4.2.2 on 2023-07-06 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nj_contacts', '0006_contact_school_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='school_head',
        ),
        migrations.AlterField(
            model_name='contact',
            name='Location',
            field=models.CharField(choices=[('Babadogo', 'Babadogo'), ('Chokaa', 'Chokaa'), ('Dandora', 'Dandora'), ('Dandora phase 1', 'Dandora phase 1'), ('Dandora phase 2', 'Dandora phase 2'), ('Dandora Phase 3', 'Dandora phase 3'), ('Kamulu', 'Kamulu'), ('Kamulu Kipawa', 'Kamulu Kipawa'), ('Kariobangi', 'Kariobangi'), ('Kariobangi South', 'Kariobangi South'), ('Kayole', 'Kayole'), ('Kayole Junction', 'Kayole Junction'), ('Kayole North', 'Kayole North'), ('KCC', 'KCC'), ('Kwa Maji', 'Kwa Maji'), ('Maili Saba', 'Maili Saba'), ('Mihango', 'Mihango'), ('Mowlem', 'Mowlem'), ('Njiru', 'Njiru'), ('Obama', 'Obama'), ('Ruai', 'Ruai'), ('Ruai Block 10', 'Ruai Block 10'), ('Saika', 'Saika'), ('Sewage', 'Sewage'), ('Silanga', 'Silanga'), ('Spring valley', 'Spring valley'), ('Umoja', 'Umoja'), ('Umoja 3', 'Umoja 3'), ('Utawala', 'Utawala'), ('Utawala githunguri', 'Utawala githunguri'), ('other', 'other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='school_code',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_school_code', message='wrong school code', regex='^20409\\d{3}$')]),
        ),
    ]
