# Generated by Django 4.2.2 on 2023-07-09 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nj_contacts', '0009_collection_points_enrolment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrolment',
        ),
    ]
