# Generated by Django 4.2.2 on 2023-07-09 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Nj_contacts', '0010_delete_enrolment'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection_points',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection_points',
            name='collection_point',
            field=models.CharField(choices=[('2040901 NJIRU D.C.C’s OFFICE', '2040901 NJIRU D.C.C’s OFFICE'), ("2040902 DANDORA ACC'S OFFICE", "2040902 DANDORA ACC'S OFFICE")], max_length=30),
        ),
        migrations.AlterField(
            model_name='collection_points',
            name='route',
            field=models.IntegerField(default=90),
        ),
    ]
