# Generated by Django 4.2.2 on 2023-07-10 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nj_contacts', '0011_collection_points_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection_points',
            new_name='KCPE_collection_point',
        ),
    ]
