# Generated by Django 4.2.2 on 2023-07-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nj_contacts', '0014_kcse_collection_point'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KEPSEA_collection_point',
        ),
    ]
